### ISSUE TITLE
Planning/todo overview

### ISSUE THREAD

**Issue by stijnvanhoey** [inbo/reporting-rshiny-woonuitbreidingsgebieden#12]
Onderstaande is de gecompileerde lijst van taken, waarbij ik de taken ook in categoriën aangeef voor de korte termijn: dev (IT developers), svh (ikzelf) en rapp (Helen/Inne):

**korte termijn:**
* technische taken
    * [ ] (dev) opwaarderen server van micro-machine naar iets performantere machine
    * [ ] (dev) authenticatie gaan we eenvoudig houden met één paswoord/gebruikersnaam voor alle gebruikers/gemeenten
    * [ ] (dev) URL voor de applicatie: hebben jullie een suggestie naar naamgeving wug.inbo.be? 
    * [ ] (dev) instellen [proxy-server/reverse proxy](http://www.shinyproxy.io/security/) (daarvoor hebben we best ook een url nodig)
    * [ ] (dev) opnemen gebruikers-statistieken, zie http://www.shinyproxy.io/usage-statistics/
    * [x] (svh) aanpakken bug binnen radar-diagram => alternatieve functie gebruiken
    * [x] (svh) consolideren ms excel in één open data formaat bestand (dus niet telkens inlezen van diverse sheets in 1 excelbestand, maar van een (puur teskstgebaseerd) formaat om opvragen data sneller te maken

* Tekstuele aanpassingen: rapp dient de teksten aan te leveren, waarna die in applicatie kunnen opgenomen worden:
    * [x] (rapp) Tekst aanleveren inleiding over de tool 
    * [x] (svh) Tekst inleiding tool toevoegen als derde tabblad
    * [x] (rapp) Disclaimer aanleveren + aangeven waar te positioneren
    * [x] (svh) Discslaimer opnemen in app
    * [x] (rapp) Het niveau provincie toe voegen als extra informatie in de bron-data (excel) van de applicatie. Momenteel enkel `ESD_Wug_Provincie` voorzien, geen `ESD_Provincie`
    * [x] (svh) in het tabblad ecosysteemdiensten voor de drop down lijst vergelijken met, ook het niveau provincie toe voegen aan de applicatie
    * [x] (rapp) Kort tekstje toevoegen met uitleg over spider diagram (generiek voor de verschillende figuren keuzes). 
    * [x] (svh) naast de spider diagram kort tekstje toevoegen met de aangeleverde uitleg (dit is generiek voor de verschillende figuren).
    * [x] (rapp) Aanleveren te gebruiken namen voor de individuele ecosysteemdiensten bij de radarchart.  
    * [x] (svh)  Opnemen van de nieuwe label namen voor de ecosysteemdiensten

**lange termijn:**
* [ ] productie keten van verzamelen, verwerken, valideren en visualiseren gegevens analyseren
* [ ] deze productieketen implementeren en zoveel mogelijk automatiseren en reproduceerbaar maken
* [ ] authenticatie per gemeente instellen
* [ ] geografische component toevoegen

Als we hier over consolideren, kunnen we evt. uitplitsen als afzonderlijke issues, maar voorlopig lijkt het me nuttig om hier mee de opvolging na te gaan.

**Comment by stijnvanhoey** [comment]
De lange termijn plannen zijn hier on hold en verder is alles in productie, closing here
